apiVersion: apps/v1
kind: Deployment
metadata:
  name: coin
spec:
  replicas: 3
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: coinbase
  template:
    metadata:
      labels:
        app: coinbase
    spec:
      containers:
        - name: http
          image: rakesh994/coinbase:27bd3b7
          ports:
            - containerPort: 80
