apiVersion: apps/v1
kind: Deployment
metadata:
  name: coin
spec:
  replicas: 3
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: coinbase
  template:
    metadata:
      labels:
        app: coinbase
    spec:
      containers:
        - name: http
          image: rakesh994/coinbase:510c061
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: coin-service
  labels:
    app.kubernetes.io/instance: coinbase-app
spec:
  selector:
    app: coinbase
  ports:
    - port: 8080 # Service port
      targetPort: 80 # Container port
      nodePort: 30080
      protocol: TCP
  type: NodePort
